KAIRA/Areas/Admin/Controllers/TestimonialController.cs
using KAIRA.Features.CQRS.Commands.TestimonialCommands;
using KAIRA.Features.CQRS.Handlers.TestimonialHandlers;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace KAIRA.Areas.Admin.Controllers;
[Area("Admin")]
public class TestimonialController: Controller
{
    private readonly GetTestimonialQueryHandler _getTestimonialQueryHandler;
    private readonly CreateTestimonialCommandHandler _createTestimonialCommandHandler;
    private readonly RemoveTestimonialCommandHandler _removeTestimonialCommandHandler;

    public TestimonialController(GetTestimonialQueryHandler getTestimonialQueryHandler, 
        CreateTestimonialCommandHandler createTestimonialCommandHandler,
        RemoveTestimonialCommandHandler removeTestimonialCommandHandler)
    {
        _getTestimonialQueryHandler = getTestimonialQueryHandler;
        _createTestimonialCommandHandler = createTestimonialCommandHandler;
        _removeTestimonialCommandHandler = removeTestimonialCommandHandler;
    }

    public async Task<IActionResult> Index()
    {
        var testimonials = await _getTestimonialQueryHandler.Handle();

        return View(testimonials);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(CreateTestimonialCommand command)
    {
        if(!ModelState.IsValid)
        {
            return View(command);
        }
        await _createTestimonialCommandHandler.Handle(command);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _removeTestimonialCommandHandler.Handle(new RemoveTestimonialCommand(id));
        return RedirectToAction(nameof(Index));
    }

    
}

KAIRA/Areas/Admin/Views/Testimonial/Create.cshtml
@model CreateTestimonialCommand
@{
    ViewData["Title"] = "değerlendirme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container top-entete mb-2">
    <div class="d-flex justify-content-center">
        <div class="d-flex align-items-center">
            <h4 class="text-primary" style="line-height:15px"><i class="fa-solid fa-plus me-2"></i>Değerlendirme Yapma İşlemi </h4>
        </div>
    </div>
</div>

<div class="container formulaire mt-3">
    <form method="post">
        <label class="form-label mb-2"> Ad</label>
        <input type="text" asp-for="@Model.Author" class="form-control mb-3" placeholder="Adınız Giriniz" />
        <span class="text-danger my-1" asp-validation-for="@Model.Author"></span> <br />
        <label class="form-label mb-2">Açıklama</label>
        <textarea class="form-control mb-3" asp-for="@Model.Comment" placeholder="Açıklama Giriniz " style="min-height:100px;"></textarea>
        <span class="text-danger my-1" asp-validation-for="@Model.Comment"></span><br />
        <div class="d-flex justify-content-center mt-3">
            <button class="btn btn-primary" type="submit">
                <i class="fa-solid fa-plus me-1"></i>
                Kaydet
            </button>
        </div>
    </form>
</div>

KAIRA/Areas/Admin/Views/Testimonial/Index.cshtml
@model List<GetTestimonialQueryResult>
@{
    ViewData["Title"] = "Değerlendirmeler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int count = 0;
}

<div class="container top-entete">
    <div class="d-flex justify-content-between">
        <div class="d-flex align-items-center">
            <h4 class="text-primary" style="line-height:15px"><i class="fa-solid fa-list-ul me-4"></i>Değerlendirmeler </h4>
        </div>
        <a asp-action="Create" asp-controller="Testimonial" asp-area="Admin" class="btn btn-outline-primary">
            <i class="fa-solid fa-plus me-1"></i>Değerlendir Ekle
        </a>

    </div>
</div>

@if (Model.Count == 0)
{
        <div class="alert alert-info mt-3 text-center" role="alert">
            <i class="fa-solid fa-circle-info me-3"></i>
            <strong>Bilgilendirme!</strong> Henüz Değerlendirme Yapılmadı!.
        </div>
}
else
{

        <div class=" mb-3 table-responsive tableau mt-3">
            <table class="table table-stripped table-hover table-sm">
                <thead class="rounded-3 tableau-header">
                    <tr>
                        <th>N°</th>
                       
                        <th>Ad Soyad</th>
                       
                        <th>Yorum</th>
                        <th>İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var testimonial in Model)
                {
                    count++;
                            <tr>
                                <th>@count</th>
                                <td class="text-primary">@testimonial.Author</td>
                                <td class="text-primary">
                                    <button class="btn btn-outline-info text-nowrap" data-bs-toggle="modal" data-bs-target="#comment-@testimonial.Id">
                                        <i class="fa-solid fa-comment me-2"></i> Oku
                                    </button>
                                </td>

                                <td class="text-nowrap">
                                    <a href="/Admin/Testimonial/Delete/@testimonial.Id" class="btn btn-danger">
                                        <i class="fa-solid fa-trash me-1"></i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                }
                </tbody>
            </table>
        </div>
    @foreach (var testimonial in Model)
    {
                <div class="modal fade" id="comment-@testimonial.Id" tabindex="-1" aria-labelledby="descriptionModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div class="d-flex justify-content-between">
                                    <h1 class="modal-title fs-5 mx-2" id="exampleModalLabel">
                                @testimonial.Author
                                    </h1>
                                </div>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <p class="fst-normal">@testimonial.Comment</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal"> <i class="fa-solid fa-xmark me-1"></i>Close</button>
                            </div>
                        </div>
                    </div>
                </div>
    }

}