KAIRA/Controllers/DefaultController.cs
using KAIRA.Features.Mediator.Commands.SubscriberCommands;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace KAIRA.Controllers;

public class DefaultController : Controller
{
    private readonly IMediator _mediator;

    public DefaultController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> Subscribe([FromBody] CreateSubscriberCommand command)
    {
        await _mediator.Send(command);

        return Json(new { success = true });   

    }
}

KAIRA/ViewComponents/BrandViewComponent.cs
using KAIRA.Features.CQRS.Handlers.BrandHandlers;
using Microsoft.AspNetCore.Mvc;

namespace KAIRA.ViewComponents;

public class BrandViewComponent: ViewComponent
{
    private readonly GetBrandQueryHandler _handler;
    public BrandViewComponent(GetBrandQueryHandler handler)
    {
        _handler = handler;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var brand = await _handler.Handle();
        return View(brand); 
    }
}

KAIRA/ViewComponents/ContactViewComponent.cs
using KAIRA.Features.Mediator.Handlers.ContactInfoHandlers;
using KAIRA.Features.Mediator.Queries.ContactInfoQueries;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace KAIRA.ViewComponents;

public class ContactViewComponent: ViewComponent
{
    private readonly IMediator _mediator;

    public ContactViewComponent(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var contact = (await _mediator.Send(new GetContactInfoQuery()))
            .OrderByDescending(c => c.Id).Take(1).First();
            return View(contact);
    }
}

KAIRA/ViewComponents/GalleryViewComponent.cs
using KAIRA.Features.Mediator.Queries.GalleryQueries;
using KAIRA.Features.Mediator.Results.GalleryResults;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace KAIRA.ViewComponents;

public class GalleryViewComponent : ViewComponent
{
    private readonly IMediator _mediator;

    public GalleryViewComponent(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var galleries = await _mediator.Send(new GetGalleryQuery());
        return View(galleries);   
    }
}

KAIRA/ViewComponents/ServiceViewComponent.cs
using KAIRA.Features.CQRS.Handlers.ServiceHandlers;
using KAIRA.Features.CQRS.Results.HizmetResults;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace KAIRA.ViewComponents;

public class ServiceViewComponent:ViewComponent
{
    private readonly GetServiceQueryHandler getServiceQueryHandler;
    public ServiceViewComponent(GetServiceQueryHandler getServiceQueryHandler)
    {
        this.getServiceQueryHandler = getServiceQueryHandler;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var services = await getServiceQueryHandler.Handle();
        return View(services);
    }
}

KAIRA/Views/Default/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
}

@await Component.InvokeAsync("BillBoard")

@await Component.InvokeAsync("Service")

@await Component.InvokeAsync("Category")

@await Component.InvokeAsync("NewArrival")

@await Component.InvokeAsync("Collection")


@await Component.InvokeAsync("BestSelling")

<section class="video py-5 overflow-hidden">
    <div class="container-fluid">
        <div class="row">
            <div class="video-content open-up" data-aos="zoom-out">
                <div class="video-bg">
                    <img src="/kaira/images/video-image.jpg" alt="video" class="video-image img-fluid">
                </div>
                <div class="video-player">
                    <a class="youtube" href="https://www.youtube.com/embed/UpwSrWlKGyg">
                        <svg width="24" height="24" viewBox="0 0 24 24">
                            <use xlink:href="#play"></use>
                        </svg>
                        <img src="/kaira/images/text-pattern.png" alt="pattern" class="text-rotate">
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

@await Component.InvokeAsync("Testimonial")



@await Component.InvokeAsync("Brand")


@await Component.InvokeAsync("Subscription")

@await Component.InvokeAsync("Gallery")

<footer id="footer" class="mt-5">
    <div class="container">
        <div class="row d-flex flex-wrap justify-content-between py-5">
            @await Component.InvokeAsync("SocialMedia")
            
            @await Component.InvokeAsync("Contact")
            
        </div>
    </div>
</footer>